### ISSUE TITLE
April meetup

### ISSUE THREAD

**Issue by leftieFriele** [nodejsoslo/meetups#1]
http://www.meetup.com/NodeJSOslo/events/229695116/
## Date  and location:

18.04 @ Teknologihuset, Oslo http://www.teknologihuset.no/#/community
## Topic:

NodeJS brukes til mer enn bare web apps, det brukes også til kritisk infrastruktur
## Talks

@ivarconr 
@phillipj 
## Sponsor

Pizza from FINN.no. FINN.no is looking for frontend developers ( http://www.finn.no/apply-here)
## Suggestions / Extra talks:

If you have a suggestion for content by yourself or others for this meetup, let us know in this issue. Any length is ok.

**Comment by leftieFriele** [comment]
Ivar fra Finn skal snakke om https://github.com/finn-no/unleash

**Comment by phillipj** [comment]
Jeg kan snakke om (1) triksene for å få Node.js ut i produksjon i en enterprise-verden hvor alt er java eller (2) bidra opensource til Node.js prosjektet.

Dere får bestemme. På norsk i denne omgang, for pysete til annet.

**Comment by leftieFriele** [comment]
Å høre om hvordan bidra i NodeJS hadde vært spennende synes jeg

**Comment by phillipj** [comment]
@leftieFriele Den er god, da sier vi det. Hvor lang tid får man til rådighet?

**Comment by leftieFriele** [comment]
Må høre med de andre, jeg er ikke Formann i fæskarlaget ;)

**Comment by leftieFriele** [comment]
@phillipj  hvis du har en abstract på Node contribute talken så kan vi annonsere!

**Comment by sveisvei** [comment]
Updated, added FINN.no as sponsor.
