### ISSUE TITLE
May meetup (security)

### ISSUE THREAD

**Issue by sveisvei** [nodejsoslo/meetups#2]
http://www.meetup.com/NodeJSOslo/events/229909583/
https://www.facebook.com/events/1753587078196313/
## Date  and location:

25.05 @ MESH (booked)
## Topic:

Node.js / Web Security
## Talks:
- @gergelyke @nthgergo Gergely Nemeth (risingstack.com)
  
  **Surviving Web Security**
  
  Security - the elephant in the room. Everyone agrees that it is very important but few takes it seriously: in the recent past a huge number of companies leaked massive amounts of user data. Let's take a look how we can survive web security - from an application developer's point of view.
  
  In this talk we are going to go through the most common web security issues and how to fix them when using Node.js. Some of these issues are among the OWASP Top 10 and pose serious risk for web applications.
  
  **About Gergely Nemeth:**
  CEO and Co-founder of RisingStack and working on Trace that makes microservice monitoring and debugging easier.
- @starefossen 
  
  **left-pad is not available (a talk about dependencies and security)**
  
  Following a trademark dispute where npm moved the kik package to a new owner the original author decided to unpublished more than 250 packages form the npm package registry - one of them the infamous left-pad with 2.5 M monthly downloads - ending up breaking an unknown number of deploys.
  
  This talk will focus on possible attack vectors by using npm and the public npm registry as well as some best practices for package maintainers when it comes to good security.
  
  About Hans Kristian Flaatten
  DevOps at @Turistforeningen where he makes and maintain all of the node microservices. An Open source enthusiast. Part of the io.js movement. Member of the Node.js Build & Docker working groups.
- @eoftedal Erlend Oftedal
  
  **Retire.js - identify JavaScript libraries with known vulnerabilities in your application** 
  
  As vulnerabilities are discovered in JavaScript libraries, it is vital that we update our dependencies. Retire.js is a command line scanner that helps you identify dependencies with known vulnerabilities in your application 
  
  **_About Erlend Oftedal**_ 
  Erlend has worked as a developer and security consultant for over 11 years, trying to build and break many different types of systems. He spends some of his free time on security research and open source tools, and is the main author behind retire.js - a free and open source scanner for JavaScript. He is also the chapter leader of the Norwegian OWASP chapter.    
## Sponsor

(Risingstack.com paying for travel etc for Gergely.)
(Turistforeningen paying for travel etc for Hans Kristian.)

(open sponsor slot)
## Suggestions / Extra talks:

If you have a suggestion for content by yourself or others for this meetup, let us know in this issue. Any length is ok.

**Comment by Starefossen** [comment]
Looking forward to this :smile: :+1:

**Comment by sveisvei** [comment]
@Starefossen there is a need from @gergelyke to reschedule to a another date, is this possible for you? 
E.g. Thursday 5. of may?

**Comment by sveisvei** [comment]
@gergelyke cant do this week (double booking), so we must either move meet up or do this in two rounds. @Starefossen Any other possible dates for you?

**Comment by Starefossen** [comment]
10th and 11th of May works for me, as well as the last week in May (week 21).

**Comment by gergelyke** [comment]
In that case how about the last week? 
I have to be at http://jsconfbp.com on the week of the 9th

**Comment by sveisvei** [comment]
We will have to change location as Teknologihuset does not have any open slots, but that could be a-ok :). 
I will check alternative locations on thursday **26.05**, please let me know if this date is foobar.

**Comment by Starefossen** [comment]
26.05 works for me. Keep me posted on the hunt for a new location. As an emergency it might be possible to use the main meeting room at The Norwegian Trekking Association's offices at Youngstorget. I can check up on what is available and how many it can fit.

**Comment by gergelyke** [comment]
Sounds good!

**Comment by gergelyke** [comment]
If it is ok for everyone, we should update the event on meetup.com as well

**Comment by sveisvei** [comment]
Sure thing, will "land" this tomorrow.

**Comment by sveisvei** [comment]
Will __25th of May__ work @gergelyke @Starefossen?
MESH is free for that date.

@gergelyke confirmed ok.

**Comment by Starefossen** [comment]
May 25th works for me 😄

**Comment by sveisvei** [comment]
Great success, then we are "a-go"!

**Comment by Starefossen** [comment]
Here is info about my talk.

---

### left-pad is not available (a talk about dependencies and security)

Following a trademark dispute where npm moved the `kik` package to a new owner the original author decided to unpublished more than 250 packages form the npm package registry - one of them the infamous `left-pad` with 2.5 M monthly downloads - ending up breaking an unknown number of deploys.

This talk will focus on possible attack vectors by using npm and the public npm registry as well as some best practices for package maintainers when it comes to good security.

**Comment by sveisvei** [comment]
So @eoftedal (https://twitter.com/webtonull) is  awesome and is joining with a talk about retire.js (http://bekk.github.io/retire.js/), so then there was 3. 

Erlend has to go last, who wants to go first @Starefossen / @gergelyke ?

**Comment by sveisvei** [comment]
@eoftedal I copy-pasted som random description and about text from the net, like to have something else there, post it to me here :)

**Comment by Starefossen** [comment]
Awesome! I have no preference regarding who goes first and second. I have one question though, should I give my presentation in Norwegian or English? Either works the same for me.

**Comment by sveisvei** [comment]
@Starefossen Depends on you of course, I prefer english - but some are not comfortable with english, so its up to you.

**Comment by gergelyke** [comment]
I am ok with going first - also, can I ask for an english speaking meetup? I'd like to understand all the stuff :)

**Comment by Starefossen** [comment]
English 🇬🇧 it is then 👍

**Comment by gergelyke** [comment]
great, thanks! :)

**Comment by sveisvei** [comment]
Thank you all! Was very high quality!

**Comment by Starefossen** [comment]
Great meetup with high quality talks! Here are the slides from my talk: https://speakerdeck.com/starefossen/leftpad-not-found
