### ISSUE TITLE
August meetup (show and tell)

### ISSUE THREAD

**Issue by sveisvei** [nodejsoslo/meetups#3]
http://www.meetup.com/NodeJSOslo/events/229994724/
## Date  and location:

30.08 @ Teknologihuset
## Topic:

Node-reel / Node.js in the wild / Node.js show and tell
## Suggestions / Talks:

@fractalf "Edderkopp - en custom web crawler skrevet i ES6/ES7"
@einari "Einar will show how to build Bots using Microsoft cognitive services deployed in Azure."
@rexxars "sse-channel (Server-Sent Events channel)"

Maybe
@eiriklv "Playing with push- and pull-streams in node"

Unconfirmed:
@viqueen "koa/react/webpack with some atlassian connect api" ?
- (open mic)

If you have a suggestion for content by yourself or others for this meetup, let us know in this issue. Any length is ok.

**Comment by popeindustries** [comment]
I'll be giving a talk at NodeConf Oslo at the beginning of June. Maybe I could do something similar?

**Comment by leftieFriele** [comment]
what about doing a talk on serverside rendering performance on React. you did some cool stuff with that which I'm sure would be interesting

**Comment by popeindustries** [comment]
sure, sounds like a good idea

**Comment by sveisvei** [comment]
@popeindustries Do you have a quick bio :)?

**Comment by popeindustries** [comment]
working on it ;) 

I'll get back to you...

**Comment by popeindustries** [comment]
@sveisvei ✉️

**Comment by sveisvei** [comment]
@eiriklv @rexxars Said they would contribute :)

**Comment by rexxars** [comment]
Yeah, I'd be happy to. I just have no clue what I find interesting in august, so maybe I can get back to it when we're a little closer to the date? :D

**Comment by eiriklv** [comment]
The same applies to me!

**Comment by fractalf** [comment]
I can show/talk about a web page crawler/parser that I made using node and ES6/7 if is of any interest

**Comment by viqueen** [comment]
I'll be in town around that time, I am thinking something something koa/react/webpack with some atlassian connect api .

**Comment by Pistus** [comment]
Can talk about some aspect of our work in @Socius where we do most things with node. Flavor of the month is [Google Cloud Functions](https://cloud.google.com/functions/docs) which we use to run a bunch of workers triggered by pubsub messages.

**Comment by sveisvei** [comment]
@Pistus Awesome, your in!

**Comment by Starefossen** [comment]
Are there still room for more speakers? I might be in Oslo on this date 😄

**Comment by fractalf** [comment]
@sveisvei Can I get an yey/ney if you want me to do a small talk? I don't know what status "thumbs up" have :)

**Comment by sveisvei** [comment]
Yay @fractalf

**Comment by sveisvei** [comment]
Indeed @starefossen !

**Comment by einari** [comment]
I can give a talk on NodeJS + Docker in Azure and consume some cognitive services. I can easily do 20 minutes or more..

**Comment by sveisvei** [comment]
@eiriklv @rexxars @viqueen @Pistus @Starefossen 
You guys still have time? Want to post a title to your show and tell contribution?

**Comment by Starefossen** [comment]
I have to pass. My trip has been re-scheduled for 1st of September - just 2 days short of this meetup 😢

**Comment by sveisvei** [comment]
Ping: @eiriklv @viqueen @Pistus

**Comment by rexxars** [comment]
I can either talk about SSE-channel or Mead, an image transforming service I'm building. Will wing it with no slides anyway, so might just ask what people want to hear about.

**Comment by Pistus** [comment]
Pfew, deep inn admin hell with the skattefunn deadline coming up and their damn webpage not actually saving when you click save.. Looks like there are some guys talking, so I will pass:/

**Comment by eiriklv** [comment]
If I'm able to make it I can talk about "Playing with push- and pull-streams in node" aka. "How I thought I discovered the message queue and now my ex employer is using it in production (don't tell anyone)". My stuff would just be ad hoc as well, with live coding/console. But I'm trying to fit a week-long React course into 3 days for a client this week, so I don't really know when or if I'm able to get to Teknologihuset :/

**Comment by sveisvei** [comment]
@Pistus To bad, thanks for responding - best of luck! Another time maybe.

@eiriklv See what you can do :). Ad hoc is the only way today... actually preferred.

**Comment by sveisvei** [comment]
@rexxars will be hosting

**Comment by sveisvei** [comment]
Thanks to the people who contributed.
