### ISSUE TITLE
June Meetup (hardware / robots)

### ISSUE THREAD

**Issue by sveisvei** [nodejsoslo/meetups#4]
http://www.meetup.com/NodeJSOslo/events/230340448/
## Date  and location:

15.06 @ Teknologihuset
## Topic:

Node.js and hardware (bots, IoT, custom servers, sensors etc)
## Talks:
- @abrabr 
  
  Open source JavaScript robotics - the over-the-counter toy edition
  
  The NodeBots movement is all around us, but did you know that you don't have to touch a soldering iron to take part? There are plenty of over-the-counter drones, robots, toys and other devices that are ready for your code, I'll show you a few.
  
  In this talk you will learn how to use JavaScript and popular open source robotics frameworks to give you that sweet instant gratification of seeing your code bridge the gap from the digital to the physical world.
  
  There will be live demos: drones, rolling robots and Minority Report style hand controls of them all.  
  Please step back!
  
  Bio: Anders is a fallen mathematician with over 10 years of experience from his backup plan as a software developer. As a consultant with the Nordic consultancy Knowit, Anders enjoys working with both large critical enterprise systems and small scale mobile solutions. Currently Anders is passionate about IoT, iBeacons and drones. He is neither an expert JavaScript-programmer or a professional pilot, but he will make those drones fly like the wind by the power of his code, and so can you.
- @markwest1972  
  How I got my Coding Mojo back my building a Node.js powered Robot!
  
  Come hear the story of how I rediscovered my Coding Mojo by building an IoT/robotics prototype: a Node.js powered, voice controlled robot. Along the way you'll learn about Johnny-Five, MQTT and not least HTML5 Voice Recognition!
  
  About Mark West: Originally from the UK, Mark is now based in Oslo where he works at Bouvet. He is a member of javaBin (the Norwegian JUG) and helps with the arrangement of both JavaZone and JavaZone Kids.
## Sponsor

Knowit will sponsor food / drinks before the meetup!

 ![knowit](http://www.knowit.no/Templates/Market/images/logo/knowit-logo.png)

Knowit is hiring for 145 positions in 2016, and so far we have only found 37 new colleagues. We are looking for a wide range of specialists, including front end developers. Are you one of them? Check out frontend.knowit.no or
send us an email at hei@knowit.no. 
## Suggestions / Extra talks:

If you have a suggestion for content by yourself or others for this meetup, let us know on this issue. Any length is ok.

**Comment by sveisvei** [comment]
Maybe either of these would like to contribute to a meetup about hardware and node.js?
https://github.com/nodeconf/oslo/issues/99 @abrabr 
https://github.com/nodeconf/oslo/issues/66 @eiriksm

**Comment by eiriksm** [comment]
Sounds like fun, and I would easily say yes, were it not for the fact that this is in Oslo and I live in Trondheim

I am flattered to be asked though, thanks ;)

**Comment by abrabr** [comment]
I would be happy to contribute, given time! September is a month of JavaZone and a couple of other conference engagements for me. Weeks 36 (5th - 9th) and 37 (12th - 16th) are taken :)

**Comment by leftieFriele** [comment]
@eiriksm we might pull off getting you down here too, if you'd be interested. But we'd have to find some money or sponsors or similar first :)

**Comment by sveisvei** [comment]
@abrabr This meetup does not "have to be" in september, we could book in second week of June as well? If June is it, we might consider the date 15. June.

If in September, maybe 21.09 would be a suitable date? Teknologihuset has a room free as well.

**Comment by eiriksm** [comment]
@leftieFriele Sorry I am answering late. Did not get a notification for that comment for some reason. But yeah, definitely interested. I'll see what I can do, sponsor-wise, with regards to my employer as well.

In September I am probably busy week 39, for the record.

**Comment by abrabr** [comment]
@leftieFriele: Sorry, both June and September are filled up for me now it
seems. Is October an option?

Knowit is hiring, I'm sure we could sponsor a meetup with pizza/beer or
something.

2016-04-06 17:58 GMT+02:00 eiriksm notifications@github.com:

**Comment by abrabr** [comment]
1. june: maybe :)

2016-04-11 14:16 GMT+02:00 Anders Breivik abr@knowit.no:

**Comment by sveisvei** [comment]
@eiriksm Are you up for a meetup around 15. of june? 

@abrabr Beer and pizza from a Knowit is a-ok.

**Comment by eiriksm** [comment]
Well, I guess the date fits. But it still in Oslo and I am in Trondheim. So still, just pointing out, I guess a more easy option organizer-wise would be to ask someone from the Oslo area :)

**Comment by sveisvei** [comment]
@abrabr I have booked Teknologihuset on the 15, but have not announced the meetup yet.

@abrabr Have any tips about local people we can ping to contribute with a talk around node.js and hardware?

**Comment by abrabr** [comment]
@sveisvei Ok, I'll reserve the 15th :) No tips, sorry. Hopefully you can find additional contributors, I only have about 20 - 30 min worth of material at best. And I'm a node.js newbie, so someone with deeper skills would complement my song-and-dance show ;)

**Comment by sveisvei** [comment]
Awesome. 20 mins is very good, we will find more then.

**Comment by TyrfingMjolnir** [comment]
I'm running NodeJS in ArchLinuxARM on RPI2 for logging of sensors, and for REST APIs under SmartOS. Is this the kind of stuff that will be discussed?

**Comment by sveisvei** [comment]
@TyrfingMjolnir I think that would fit. This is an open meetup group, so if YOU would like to tell, I at least would like to hear :).

**Comment by markwest1972** [comment]
Really cool that you guys are doing this!  

If you are interested I can present my NodeBot Rover, which uses Johnny-Five on the software side and Arduino / Raspberry PI on the hardware side.  I've presented the same Robot at JavaOne and the IoT Tech Day in The Netherlands.  In both cases I received extremely positive feedback.

My talk is 45 minutes long, but I can trim it down to 20 minutes if needs be.  The slides are here : http://www.slideshare.net/markawest/iot-tech-day-coding-mojo-slides-utrecht-april-2016.

Alternatively I can also present my lighting talk about Johnny-Five from JavaZone 2015 : https://vimeo.com/album/3190253/video/138862373. 

Edit : My twitter account is @markawest BTW :)

**Comment by sveisvei** [comment]
@markwest1972 Goodie, about 20 mins is a nice length for talks here I think, but nothing is set in stone.

**Comment by TyrfingMjolnir** [comment]
But is it this the kind of stuff that would be on topic for this meetup?

**Comment by sveisvei** [comment]
@TyrfingMjolnir Yes. I think bots, "IoT", custom hardware/servers and sensors are within our topic.

**Comment by markwest1972** [comment]
@sveisvei If you decide to have me along then let me know which talk / format you'd like.  At that point I can put together a quick abstract for your Meetup page.  There's no major hurry from my side - as long as I know by mid May I'll be happy :)

In the meantime I'll register for the Meetup and block off the date in my calendar.

**Comment by sveisvei** [comment]
@markwest1972 Give me title, short text + bio and I will put it up asap.

**Comment by markwest1972** [comment]
Ok, here's a quick writeup for a 20 minute version of the Coding Mojo talk.  

**Title:** How I got my Coding Mojo back my building a Node.js powered Robot!

**Abstract:** Come hear the story of how I rediscovered my Coding Mojo by building an IoT/robotics prototype: a Node.js powered, voice controlled robot. Along the way you'll learn about Johnny-Five, MQTT and not least HTML5 Voice Recognition!

**Bio:** Originally from the UK, Mark is now based in Oslo where he works at Bouvet. He is a member of javaBin (the Norwegian JUG) and helps with the arrangement of both JavaZone and JavaZone Kids.

**Comment by sveisvei** [comment]
@abrabr Could you also give me a title, abstract + bio :)?

**Comment by abrabr** [comment]
Looking forward to seeing your talk, @markwest1972!

@sveisvei, certainly! Are the talks usually held in English?

**Title**: Open source JavaScript robotics - the over-the-counter toy edition

**Abstract**: The NodeBots movement is all around us, but did you know that you don't have to touch a soldering iron to take part? There are plenty of over-the-counter drones, robots, toys and other devices that are ready for your code, I'll show you a few.

In this talk you will learn how to use JavaScript and popular open source robotics frameworks to give you that sweet instant gratification of seeing your code bridge the gap from the digital to the physical world.

There will be live demos: drones, rolling robots and Minority Report style hand controls of them all. Please step back!

**Bio**: Anders is a fallen mathematician with over 10 years of experience from his backup plan as a software developer. As a consultant with the Nordic consultancy Knowit, Anders enjoys working with both large critical enterprise systems and small scale mobile solutions. Currently Anders is passionate about IoT, iBeacons and drones. He is neither an expert JavaScript-programmer or a professional pilot, but he will make those drones fly like the wind by the power of his code, and so can you.

**Comment by sveisvei** [comment]
@abrabr English if possible I guess, but if you prefer norwegian that is possible as well. Better to talk in norwegian than not to talk at all :).

@abrabr Should we formalise KnowIt bringing some food/beer or maybe something to play with or giveaways (hint hint: tessel 2), and what they/you expect in return. We can take this conversation on email if you want that.

**Comment by markwest1972** [comment]
BTW I'm happy with holding my talk English or Norwegian.  Just let me know what you prefer.

**Comment by abrabr** [comment]
Either language works for me :) 

@sveisvei, indeed! Lets do that discussion by email: abr@knowit.no.

**Comment by markwest1972** [comment]
One more thing - are talks about Node-Red solutions in or out of scope for this Meetup?  Asking for a friend...

**Comment by sveisvei** [comment]
English it is!
But if anyone else comes later and wants to talk in norwegian, that is a-ok as well, just to be clear :).

@markwest1972 invite your friend in here, I would like to know more about http://nodered.org/ tbh.

**Comment by markwest1972** [comment]
@abrabr We should perhaps collaborate to reduce duplication in our talks.  My slides for the 45 minute version of my talk can be found here : http://www.slideshare.net/markawest/iot-tech-day-coding-mojo-slides-utrecht-april-2016.  

To bring my talk down to 20 minutes I'm thinking about focusing on the Hardware, Johnny-Five and Firmata aspects (slides 12-31).  If I have time I'll also talk a bit about HTML5 speech recognition (33-41).

Context wise, my angle is all about how J5 can open up hardware for JavaScript programmers, and how it can be used as a tool for attracting people to the Node.js space.

**Comment by markwest1972** [comment]
I've created a version of my talk for the meetup.  It's about 20-25 minutes long - hope thats OK.  All my demos will be videos on Vimeo.  I'll leave it to @abrabr to blow everyones minds with his live show :)

Here's a PDF version of my slides : http://www.slideshare.net/markawest/coding-mojo-nodejs-meetup.  I'll post this link on the Meetup page after I've given the presentation.

See you in a couple weeks!

**Comment by sveisvei** [comment]
@markwest1972 nice, awesome! 

@markwest1972 @abrabr Should we rename the title of the meetup maybe? "Javascript and robots"?

**Comment by markwest1972** [comment]
@sveisvei possibly.  Are there any other potential speakers in the pipeline?  Maybe someone who wants to talk about Node.js and IOT?

**Comment by sveisvei** [comment]
@markwest1972 Not atm, but was thinking that 1 more for this meetup would be perfect. Tips welcome, and I will try to search for potential people to nudge this way.

**Comment by markwest1972** [comment]
I've posted on LinkedIn and Twitter.  I've got **very** few followers, but maybe something will turn up.

**Comment by sveisvei** [comment]
@abrabr @markwest1972 Ready for tomorrow?

@abrabr Any thoughts around sponsoring food tomorrow? Does not look to be a large crowd anyhow.

**Comment by markwest1972** [comment]
Alt klar fra min side!

**Comment by abrabr** [comment]
@sveisvei, @markwest1972 Sorry about my absence from this thread, busy days!

Yes I'm ready for today, charging my drones as we speak :)

@markwest1972 I'll try to avoid duplicating point from your talk. My talk will focus on js/node.js/cylon.js and over the counter toys as the path of least resistance to robotics.

**Comment by sveisvei** [comment]
Thanx to both of you for doing this, inspiring stuff and impressive that you talk in a node group being "non native".

Hope to see you some time later.
