### ISSUE TITLE
September Meetup (universal/shared code) 

### ISSUE THREAD

**Issue by sveisvei** [nodejsoslo/meetups#7]
## Date  and location:

September @ Startuplab
## Topic:

Universal / Shared code server and client
## Talks:

@popeindustries 
? open slot
? open slot
## Host:

@areo / @klokoy
## Sponsor:

(open slot if you want to pay for food/drinks)
## Suggestions:

If you have a suggestion for content by yourself or others for this meetup, let us know on this issue. Any length is ok.

**Comment by popeindustries** [comment]
Instead of show and tell? Sounds good. 

Do you have a tentative date?

**Comment by sveisvei** [comment]
@popeindustries I was thinking this topic deserves a dedicated evening. 

Concerning dates, Im thinking the within the timeframe 15.08-25.08. Do you have any suggestions? We should check against @klokoy also :).

**Comment by popeindustries** [comment]
That timeframe works for me!

**Comment by klokoy** [comment]
Any day except 22.08 is good for me.

**Comment by sveisvei** [comment]
Im thinking 24.08 then, vacation time should be over by then.

**Comment by sveisvei** [comment]
How is everything here? I am thinking we should move this meetup to september, objections/ ideas/suggestions?

**Comment by popeindustries** [comment]
September could be busy, but let's give it a try

**Comment by klokoy** [comment]
September is good for me. The 15.th September the StartupLab is occupied, so we need to stay clear of this day;)

**Comment by sveisvei** [comment]
Closing this, RL / lack of interest stopped this.
